server.port: 8080

filmorate:
  default.popular-list-count: 10

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  application.name: Filmorate
  sql.init.mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 1500
  h2:
    console:
      enabled: false