-- mpas
INSERT INTO PUBLIC.MPAS (NAME)
SELECT 'G' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.MPAS WHERE NAME = 'G'
);
INSERT INTO PUBLIC.MPAS (NAME)
SELECT 'PG' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.MPAS WHERE NAME = 'PG'
);
INSERT INTO PUBLIC.MPAS (NAME)
SELECT 'PG-13' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.MPAS WHERE NAME = 'PG-13'
);
INSERT INTO PUBLIC.MPAS (NAME)
SELECT 'R' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.MPAS WHERE NAME = 'R'
);
INSERT INTO PUBLIC.MPAS (NAME)
SELECT 'NC-17' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.MPAS WHERE NAME = 'NC-17'
);
-- genres
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Комедия' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Комедия'
);
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Драма' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Драма'
);
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Мультфильм' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Мультфильм'
);
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Триллер' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Триллер'
);
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Документальный' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Документальный'
);
INSERT INTO PUBLIC.GENRES (NAME)
SELECT 'Боевик' WHERE NOT EXISTS (
    SELECT 1 FROM PUBLIC.GENRES WHERE NAME = 'Боевик'
);