--
CREATE TABLE IF NOT EXISTS public.users (
	user_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
	login    VARCHAR(50)  NOT NULL,
	name     VARCHAR(50)  NOT NULL,
	email    VARCHAR(50)  NOT NULL,
	birthday DATE         NOT NULL
);
--
CREATE TABLE IF NOT EXISTS public.friendships (
	friendship_id BIGINT NOT NULL AUTO_INCREMENT,
	user_id       BIGINT NOT NULL,
	friend_id     BIGINT NOT NULL,
	CONSTRAINT FRIENDSHIPS_PK PRIMARY KEY (FRIENDSHIP_ID),
	CONSTRAINT FRIENDSHIPS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FRIENDSHIPS_USERS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS public.mpas (
	mpa_id INT AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(50)  NOT NULL UNIQUE
);
--
CREATE TABLE IF NOT EXISTS public.genres (
	genre_id INT AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(50)  NOT NULL UNIQUE
);
--
CREATE TABLE IF NOT EXISTS public.films (
	film_id      BIGINT AUTO_INCREMENT PRIMARY KEY,
	name         VARCHAR(50)  NOT NULL,
	description  VARCHAR(255) NOT NULL,
	release_date DATE         NOT NULL,
	duration     INTEGER      NOT NULL,
	mpa_id       INTEGER,
	rank         INTEGER DEFAULT 0,
	CONSTRAINT MPAS_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPAS(MPA_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS public.films_genres (
	film_id      BIGINT   NOT NULL,
	genre_id     INTEGER  NOT NULL,
	CONSTRAINT FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT GENRES_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS public.likes (
	user_id BIGINT NOT NULL,
	film_id BIGINT NOT NULL,
    CONSTRAINT USERS_FK_2 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILMS_FK_1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);