--
CREATE TABLE IF NOT EXISTS users (
	user_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
	login    VARCHAR(50)  NOT NULL,
	name     VARCHAR(50)  NOT NULL,
	email    VARCHAR(50)  NOT NULL,
	birthday DATE         NOT NULL
);
--
CREATE TABLE IF NOT EXISTS friendships (
	friendship_id BIGINT NOT NULL AUTO_INCREMENT,
	user_id       BIGINT NOT NULL,
	friend_id     BIGINT NOT NULL,
	CONSTRAINT FRIENDSHIPS_PK PRIMARY KEY (FRIENDSHIP_ID),
	CONSTRAINT FRIENDSHIPS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FRIENDSHIPS_USERS_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS mpas (
	mpa_id INT AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(50)  NOT NULL UNIQUE
);
--
CREATE TABLE IF NOT EXISTS genres (
	genre_id INT AUTO_INCREMENT PRIMARY KEY,
	name   VARCHAR(50)  NOT NULL UNIQUE
);
--
CREATE TABLE IF NOT EXISTS films (
	film_id      BIGINT AUTO_INCREMENT PRIMARY KEY,
	name         VARCHAR(50)  NOT NULL,
	description  VARCHAR(255) NOT NULL,
	release_date DATE         NOT NULL,
	duration     INTEGER      NOT NULL,
	mpa_id       INTEGER,
	liked        BIGINT DEFAULT 0,
	CONSTRAINT MPAS_FK FOREIGN KEY (MPA_ID) REFERENCES MPAS(MPA_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS films_genres (
	film_id      BIGINT   NOT NULL,
	genre_id     INTEGER  NOT NULL,
	CONSTRAINT FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT GENRES_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
--
CREATE TABLE IF NOT EXISTS likes (
	like_id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	film_id BIGINT NOT NULL,
    CONSTRAINT USERS_FK_2 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILMS_FK_1 FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    useful INTEGER DEFAULT 0,
    CONSTRAINT USER_ID_FK_REV FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILM_ID_FK_REV FOREIGN KEY (film_id) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT REVIEW_USER_FILM_UNIQUE UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS review_marks (
    review_id BIGINT,
    user_id BIGINT,
    is_useful BOOLEAN,
    CONSTRAINT REVIEW_ID_FK_MARK FOREIGN KEY (review_id) REFERENCES REVIEWS(review_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT USER_ID_FK_MARK FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (user_id, review_id)
--
CREATE TABLE IF NOT EXISTS directors (
    director_id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    director_name VARCHAR(100)  NOT NULL UNIQUE
);
--
CREATE TABLE IF NOT EXISTS director_films (
    film_id     BIGINT  REFERENCES films (film_id)         ON DELETE CASCADE NOT NULL,
    director_id BIGINT  REFERENCES directors (director_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (film_id, director_id)
);